### PR TITLE
chore: Upgrade nock

### PR DESCRIPTION
**Pull request by koooge**
Upgrade nock due to warning with node12

```
$ npm run test
(node:86033) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(node:86032) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(node:86035) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

### CODE REVIEW

**Comment by koooge** [comment]
Oh... nock has droped node6 support 
https://github.com/nock/nock/commit/4fbaac6c4604e0acc9732cc1941da78a44d6d977#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by H1Gdev** [comment]
@koooge 
@vlucas 

`node6` is already `End-of-Life`.
I think that frisby can finish supporting `node6`.

**Comment by vlucas** [comment]
Agreed. We can drop node 6 support.

**Comment by vlucas** [comment]
We will go ahead and do a major version bump for this too, so we will need to publish frisby 2.2.0.

**Pull request merged**
