### PR TITLE
Make v2 expect('jsonTypes'...) behave like v1 expectJSONTypes(...)

### PR DESCRIPTION
**Pull request by schmollmolch**
The default behavior in frisby v1 expectJSONTypes was to check the given types but ignore any none-specified key. Using Joi's 'allowUnknown' option should recreate that behavior.

### CODE REVIEW

**Comment by schmollmolch** [comment]
Also I added the headers of the previous response as second parameter provided by ".then(...)". I do not feel 100% happy with thta solution though, as it is no longer Promise-like

**Comment by vlucas** [comment]
I am okay with adding `allowUnknown` so it works like Frisby v1, but I am not okay with adding more arguments since it's not Promise-like. We may have to return a custom response object instead, or have some kind of `getResponse` functions that returns the real Fetch Response object.

**Comment by schmollmolch** [comment]
Alright, I removed that un-Promise-like header provisioning but having `allowUnknown` would still be beneficial.

**Comment by vlucas** [comment]
Thanks. Merged. We may also want to make a separate `jsonTypesStrict` rule that will behave like this used to.

**Pull request merged**
