### PR TITLE
Load JSON Schema files globally

### PR DESCRIPTION
**Pull request by imranolas**
Schemas can have references to other schemas. This change lets us load the required schemas in advance making them available when needed.

```js
frisby.loadJSONSchema({
  "product": productSchema,
  "item": ItemSchema
});
```

For example, wherever a schema references (`$refs`), `"product"`, `productSchema` will be substituted. Partly addresses #100 although the schemas still need to loaded manually.

### CODE REVIEW

**Comment by igorkosta** [comment]
Hi @imranolas,

I'm wondering why I'm getting a `[TypeError: Object #<Object> has no method 'loadJSONSchema']` by trying to load the required schemas with ```frisby.loadJSONSchema({
 "schemaToLoad": schemaToLoad
});```
although according to `package.json` I'm using the version ```  "name": "frisby",
  "version": "0.8.5"``` which supposedly have to contain the `loadJSONSchema` method.

Thanks in advance!
Cheers
Igor

**Comment by vlucas** [comment]
I cannot merge this without tests. @imranolas can you add some test for this to prove that it works the way you intend it to?

**Comment by imranolas** [comment]
@vlucas Sorry for the delay. I'm happy to add some tests for this, however, there is an issue with the test suite.

`frisby.create()` declarations that are nested within jasmine `it` blocks have their errors swallowed and consequently the suite always passes. I'm not sure what the easiest solution is, ie. pass the errors back up the stack or catch errors with promises. Any thoughts?

**Comment by nickveenhof** [comment]
I'm using this PR to validate my tests. It's a blocker for full fledged API testing. I am not a very good JS developer but happy to review any tests that are added. The one thing I don't like about this is the fact that this is requiring to look to your json schema files to see which files you need to include. Not very flexible

**Pull request closed without merging**
